# Generated by Django 3.1.2 on 2020-10-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccessId', models.IntegerField()),
                ('DateAccessed', models.DateTimeField()),
                ('RFIDUsed', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComponentId', models.IntegerField()),
                ('Name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=32)),
                ('Rg', models.CharField(max_length=32)),
                ('Email', models.CharField(max_length=64)),
                ('Password', models.CharField(max_length=32)),
                ('PasswordHint', models.CharField(max_length=32)),
            ],
        ),
    ]
