# Generated by Django 3.1.2 on 2020-10-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessHistory',
            new_name='Access',
        ),
    ]
