# Generated by Django 3.1.2 on 2020-10-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeAPI', '0002_auto_20201003_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Access',
            new_name='AccessHistory',
        ),
    ]
