# Generated by Django 3.1.2 on 2020-11-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeAPI', '0003_auto_20201003_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='UserId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
