# Generated by Django 3.1.2 on 2020-11-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeAPI', '0006_auto_20201129_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
